# Generated by Django 4.1.7 on 2023-03-29 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mail',
            field=models.EmailField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='red_social',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
